apiVersion: v1
kind: Service
metadata:
  name: evil-ai-rag-api
  labels:
    app: evil-ai-rag
spec:
  type: ClusterIP
  selector:
    app: evil-ai-rag
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
